spring:
  application:
    name: ResisasBot

  profiles:
    active: prod

  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    org.springframework.web: ERROR

server:
  port: ${PORT:8080}

resisas:
  web:
    welcome-config-url: ${WELCOME_CONFIG_URL:https://resisasbot.com/welcome}

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${RAILWAY_TCP_PROXY_DOMAIN}:${RAILWAY_TCP_PROXY_PORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://${TESTING_RAILWAY_TCP_PROXY_DOMAIN}:${TESTING_RAILWAY_TCP_PROXY_PORT}/${TESTING_PGDATABASE}
    username: ${TESTING_PGUSER}
    password: ${TESTING_PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
